# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/c/DPU-PYNQ/boards/Ultra96v2/binary_container_1/link/vivado/vpl/prj/prj.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5.xci
# IP: The module: 'design_1_auto_ds_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/c/DPU-PYNQ/boards/Ultra96v2/binary_container_1/link/vivado/vpl/prj/prj.gen/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/c/DPU-PYNQ/boards/Ultra96v2/binary_container_1/link/vivado/vpl/prj/prj.gen/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/c/DPU-PYNQ/boards/Ultra96v2/binary_container_1/link/vivado/vpl/prj/prj.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5.xci
# IP: The module: 'design_1_auto_ds_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/c/DPU-PYNQ/boards/Ultra96v2/binary_container_1/link/vivado/vpl/prj/prj.gen/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/c/DPU-PYNQ/boards/Ultra96v2/binary_container_1/link/vivado/vpl/prj/prj.gen/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
